// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Sisyphus.Spec
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Event")]
    public partial class EventFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EventStory.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Event", "In order to describe the structure of a story and tie together interactions of gr" +
                    "oups of characters\r\nAs a writer\r\nI want to be able to edit events and add dialog" +
                    "ue/narrative to them", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I have set up configuration to use testConfig", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And("I set the config key \"SessionTimeout\" to \"15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I set ContextWrapper To use TestContextWrapper", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I set the user Identity to \"writer@admin.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I have set SisyphusDateTime to TestDateTime", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I have set the date to year \"2014\" Month \"7\" Day \"20\" hour \"19\" minute \"24\" secon" +
                    "d \"12\" millisecond \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I have created a test database called \"eventCreation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I create a user with email \"writer@admin.com\" with password \"testtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "role"});
            table1.AddRow(new string[] {
                        "Admin"});
            table1.AddRow(new string[] {
                        "Writer"});
            table1.AddRow(new string[] {
                        "Reader"});
#line 15
 testRunner.And("I assign the following roles to user \"writer@admin.com\"", ((string)(null)), table1, "And ");
#line 20
 testRunner.And("I log in with the user \"writer@admin.com\" and password \"testtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("I use the controller WriterHome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "backStory"});
            table2.AddRow(new string[] {
                        "test1",
                        "ooo itS BACK STORY"});
            table2.AddRow(new string[] {
                        "test2",
                        "COR HE THINKS ITS A WEAL STOWY"});
#line 22
 testRunner.And("I have created the stories", ((string)(null)), table2, "And ");
#line 26
 testRunner.And("I select the story \"test1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "history"});
            table3.AddRow(new string[] {
                        "testPlace",
                        "history1"});
            table3.AddRow(new string[] {
                        "testPlace2",
                        "history2"});
#line 27
 testRunner.And("I create the following places", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "backstory"});
            table4.AddRow(new string[] {
                        "foot",
                        "bulling you rleg"});
#line 31
 testRunner.And("I create the following races", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "description"});
            table5.AddRow(new string[] {
                        "rarley",
                        "nto often"});
            table5.AddRow(new string[] {
                        "bannanas",
                        "yellowZ"});
#line 34
 testRunner.And("I create the following sexes", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "backstory",
                        "race",
                        "sex",
                        "place"});
            table6.AddRow(new string[] {
                        "jim",
                        "none",
                        "foot",
                        "rarley",
                        "somewhere"});
            table6.AddRow(new string[] {
                        "jim2",
                        "none",
                        "foot",
                        "bannanas",
                        "somewhere"});
            table6.AddRow(new string[] {
                        "jim3",
                        "none",
                        "foot",
                        "rarley",
                        "somewhere"});
            table6.AddRow(new string[] {
                        "jim4",
                        "none",
                        "foot",
                        "bannanas",
                        "somewhere"});
#line 38
 testRunner.And("I create the following characters", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "Description",
                        "Outcomes",
                        "Duration"});
            table7.AddRow(new string[] {
                        "testEvent",
                        "a test event to show how things work",
                        "passed, failed, war",
                        "3"});
#line 44
 testRunner.And("I create the following events", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "name"});
            table8.AddRow(new string[] {
                        "jim"});
            table8.AddRow(new string[] {
                        "jim3"});
#line 47
 testRunner.And("I add the following characters to the event \"testEvent\"", ((string)(null)), table8, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add dialogue to an event")]
        public virtual void AddDialogueToAnEvent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add dialogue to an event", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "dialog"});
            table9.AddRow(new string[] {
                        "0",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 53
 testRunner.When("I add to the event \"testEvent\" from perspective of \"jim\" the following lines of d" +
                    "ialogue", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table10.AddRow(new string[] {
                        "0",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 56
 testRunner.Then("I expect \"jim\" to have the following story for the event \"testEvent\"", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add dialogue to an event with multiple characters (dialogue is shared (objective)" +
            ")")]
        public virtual void AddDialogueToAnEventWithMultipleCharactersDialogueIsSharedObjective()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add dialogue to an event with multiple characters (dialogue is shared (objective)" +
                    ")", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "dialog"});
            table11.AddRow(new string[] {
                        "0",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 61
 testRunner.When("I add to the event \"testEvent\" from perspective of \"jim\" the following lines of d" +
                    "ialogue", ((string)(null)), table11, "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table12.AddRow(new string[] {
                        "0",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 64
 testRunner.Then("I expect \"jim\" to have the following story for event \"testEvent\"", ((string)(null)), table12, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table13.AddRow(new string[] {
                        "0",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 67
 testRunner.And("I expect \"jim3\" to have the following story for event \"testEvent\"", ((string)(null)), table13, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Narrative to an event")]
        public virtual void AddNarrativeToAnEvent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Narrative to an event", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table14.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 72
 testRunner.When("I add to the event \"testEvent\" from perspective of \"jim\" the following Narrative", ((string)(null)), table14, "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table15.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 75
 testRunner.Then("I expect \"jim\" to have the following story for event \"testEvent\"", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Narrative to an event with 2 chars - but only 1 narrative (so both get that n" +
            "arrative as a convinience)")]
        public virtual void AddNarrativeToAnEventWith2Chars_ButOnly1NarrativeSoBothGetThatNarrativeAsAConvinience()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Narrative to an event with 2 chars - but only 1 narrative (so both get that n" +
                    "arrative as a convinience)", ((string[])(null)));
#line 79
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table16.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 80
 testRunner.When("I add to the event \"testEvent\" from perspective of \"jim\" the following Narrative", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table17.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 83
 testRunner.Then("I expect \"jim\" to have the following story for event \"testEvent\"", ((string)(null)), table17, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table18.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 86
 testRunner.And("I expect \"jim3\" to have the following story for event \"testEvent\"", ((string)(null)), table18, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add narative and dialogue to an event with 2 chars - sequence test")]
        public virtual void AddNarativeAndDialogueToAnEventWith2Chars_SequenceTest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add narative and dialogue to an event with 2 chars - sequence test", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table19.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 91
 testRunner.When("I add to the event \"testEvent\" from perspective of \"jim\" the following Narrative", ((string)(null)), table19, "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "dialog"});
            table20.AddRow(new string[] {
                        "1",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 94
 testRunner.And("I add to the event \"testEvent\" from perspective of \"jim\" the following lines of d" +
                    "ialogue", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table21.AddRow(new string[] {
                        "2",
                        "look its some more story"});
#line 97
 testRunner.And("I add to the event \"testEvent\" from perspective of \"jim\" the following Narrative", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table22.AddRow(new string[] {
                        "0",
                        "look its some story"});
            table22.AddRow(new string[] {
                        "1",
                        "Jim says \"Its awfully lonley in this scenario\""});
            table22.AddRow(new string[] {
                        "2",
                        "look its some more story"});
#line 100
 testRunner.Then("I expect \"jim\" to have the following story for event \"testEvent\"", ((string)(null)), table22, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table23.AddRow(new string[] {
                        "0",
                        "look its some story"});
            table23.AddRow(new string[] {
                        "1",
                        "Jim says \"Its awfully lonley in this scenario\""});
            table23.AddRow(new string[] {
                        "2",
                        "look its some more story"});
#line 105
 testRunner.And("I expect \"jim3\" to have the following story for event \"testEvent\"", ((string)(null)), table23, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 characters shared dialog but unique narrative for both")]
        public virtual void _2CharactersSharedDialogButUniqueNarrativeForBoth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 characters shared dialog but unique narrative for both", ((string[])(null)));
#line 111
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table24.AddRow(new string[] {
                        "0",
                        "look its some story"});
#line 112
 testRunner.When("I add to the event \"testEvent\" from perspective of \"jim\" the following Narrative", ((string)(null)), table24, "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table25.AddRow(new string[] {
                        "1",
                        "look its some other story"});
#line 115
 testRunner.And("I add to the event \"testEvent\" from perspective of \"jim3\" the following Narrative" +
                    "", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "dialog"});
            table26.AddRow(new string[] {
                        "2",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 118
 testRunner.And("I add to the event \"testEvent\" from perspective of \"jim\" the following lines of d" +
                    "ialogue", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "narrative"});
            table27.AddRow(new string[] {
                        "3",
                        "look its some more story"});
#line 121
 testRunner.And("I add to the event \"testEvent\" from perspective of \"jim\" the following Narrative", ((string)(null)), table27, "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table28.AddRow(new string[] {
                        "0",
                        "look its some story"});
            table28.AddRow(new string[] {
                        "2",
                        "Jim says \"Its awfully lonley in this scenario\""});
            table28.AddRow(new string[] {
                        "3",
                        "look its some more story"});
#line 124
 testRunner.Then("I expect \"jim\" to have the following story for event \"testEvent\"", ((string)(null)), table28, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "eventStepIndex",
                        "story lines"});
            table29.AddRow(new string[] {
                        "1",
                        "look its some other story"});
            table29.AddRow(new string[] {
                        "2",
                        "Jim says \"Its awfully lonley in this scenario\""});
#line 129
 testRunner.And("I expect \"jim3\" to have the following story for event \"testEvent\"", ((string)(null)), table29, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
